phraseapp:
  project_id: bb68378bb70334cea139425cf31c843c
  file_format: "xml"
  push:
    sources:
    - file: "./Android/values/strings.xml"
    - file: "./Android/values-pl/strings.xml"
  pull:
    targets:
    - file: "./Android/values/strings.xml"
    - file: "./Android/values-pl/strings.xml"
